[package]
name = "vaic"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.12.0"
bevy_infinite_grid = { git = "https://github.com/elodin-sys/bevy_infinite_grid.git", version = "0.9" } # Until updated to 0.12
smooth-bevy-cameras = { git = "https://github.com/Aztro-dev/smooth-bevy-cameras.git", branch = "bevy-0.12" }
bevy_transform_gizmo = { git = "https://github.com/rszemplinski/bevy_transform_gizmo.git", branch = "main" } # Until updated to 0.12
bevy_mod_picking = "0.17.0"
bevy_prototype_lyon = "0.10.0"
bevy_mod_raycast = "0.16.0"
